// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI0N0sRLjHvf9BD_ZGp6JyoIVh-CTDYxE',
    appId: '1:36324875987:web:1d877704437deceb9ebe26',
    messagingSenderId: '36324875987',
    projectId: 'iims-flutter-project',
    authDomain: 'iims-flutter-project.firebaseapp.com',
    databaseURL: 'https://iims-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'iims-flutter-project.appspot.com',
    measurementId: 'G-B299EBN6NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DNF4mJ3DPLwioZcYKhYAwysE_UFl8gs',
    appId: '1:36324875987:android:1bd786177f4218c99ebe26',
    messagingSenderId: '36324875987',
    projectId: 'iims-flutter-project',
    databaseURL: 'https://iims-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'iims-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDzJFd3bGPMdZ4pdx6LCPC7J3ZB0SZbIs',
    appId: '1:36324875987:ios:3b9e904fc5d0c3ca9ebe26',
    messagingSenderId: '36324875987',
    projectId: 'iims-flutter-project',
    databaseURL: 'https://iims-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'iims-flutter-project.appspot.com',
    iosClientId: '36324875987-ohn95bpc185pb76e8oiujr2kjle0cmt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeAppIims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDzJFd3bGPMdZ4pdx6LCPC7J3ZB0SZbIs',
    appId: '1:36324875987:ios:fffb89e51e988b6f9ebe26',
    messagingSenderId: '36324875987',
    projectId: 'iims-flutter-project',
    databaseURL: 'https://iims-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'iims-flutter-project.appspot.com',
    iosClientId: '36324875987-l1pnes48tp3eju0kkdnot9virb36eqj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeAppIims.RunnerTests',
  );
}
